# Generated by Django 3.0.6 on 2020-06-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='GuestEmail',
        ),
    ]
