# Generated by Django 3.0.6 on 2020-06-07 12:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200607_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='abc', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
